
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'LeaveManagementSystem')
BEGIN 
	DROP DATABASE LeaveManagementSystem
END
GO
CREATE DATABASE LeaveManagementSystem
GO
USE LeaveManagementSystem
GO

IF EXISTS(SELECT * FROM  DBO.SYSOBJECTS WHERE NAME = 'USERID')
BEGIN
	DROP TABLE USERID
END
CREATE TABLE USERID(
ID_USER		INT,   --TU TANG
USRNAME		NVARCHAR(30),
PASSWORD	NVARCHAR(30),
ID_POSITION	INT

PRIMARY KEY(ID_USER)
)
GO
IF EXISTS(SELECT * FROM  DBO.SYSOBJECTS WHERE NAME = 'POSITION')
BEGIN
DROP TABLE POSITION
END
CREATE TABLE POSITION(
ID_POSITON		INT,
NAME_POSITON	NVARCHAR(30)
PRIMARY KEY(ID_POSITON)
)
GO
IF EXISTS(SELECT * FROM  DBO.SYSOBJECTS WHERE NAME = 'LEAVEAPP')
BEGIN
DROP TABLE LEAVEAPP
END
CREATE TABLE LEAVEAPP(
ID_LA		INT,     --TU TANG
ID_USER		INT,
DATEFORM	DATETIME,
SUNDAYOFF	INT,
REASON		NVARCHAR(MAX),
STATUS		NVARCHAR(7),
ADDRESS		NVARCHAR(50),
PHONE		NVARCHAR(20)
PRIMARY KEY(ID_LA)
)
GO
IF EXISTS(SELECT * FROM  DBO.SYSOBJECTS WHERE NAME = 'EMPLOYEE')
BEGIN
DROP TABLE EMPLOYEE
END
CREATE TABLE EMPLOYEE(     
ID_USER		INT,     
FULLNAME	NVARCHAR(50),
BIRTHDAY	DATETIME,
ADDRESS		NVARCHAR(50),
SEX			NVARCHAR(10),
PHONE		NVARCHAR(20),
EMAIL		NVARCHAR(50)
PRIMARY KEY(ID_USER)
)
GO
IF EXISTS(SELECT * FROM  DBO.SYSOBJECTS WHERE NAME = 'CATCH')
BEGIN
DROP TABLE CATCH
END
CREATE TABLE CATCH(     
ID			INT,     
CMONTH		INT,
CYEAR		INT,
LEGELDAYOFF		INT,
ILLEGALDAYOFF	INT
PRIMARY KEY(ID,CMONTH,CYEAR)
)